// packages/kagura-ui-react/src/components/Button.tsx
import { ColorKeys, Size, ButtonVariant } from "@kagura-ui/core/contracts";
import { ButtonHTMLAttributes } from "react";

export interface ButtonProps
  extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "color"> {
  size?: Size;
  color?: ColorKeys;
  variant?: ButtonVariant;
  classes?: Partial<ButtonClasses>;
}
interface ButtonClasses {
  root: string;
  inner: string;
  label: string;
}

export const Button = ({
  size = "md",
  children,
  className,
  color = "primary",
  variant = "filled",
  classes = {},
  ...props
}: ButtonProps) => {
  return (
    <button
      className={`[ button ] [ ${classes.root || ""} ]`}
      data-variant={variant}
      data-size={size}
      data-color={color}
      {...props}
    >
      <div className={`[ button-inner ] [ ${classes.inner || ""} ]`}>
        <span className={`[ button-label ] [ ${classes.label || ""} ]`}>
          {children}
        </span>
      </div>
    </button>
  );
};

// packages/kagura-ui-svelte/src/lib/Button.svelte
<script lang="ts">
	import type { ButtonVariant, Size, ColorKeys } from '@kagura-ui/core/contracts';
	export let color: ColorKeys = 'primary';
	export let variant: ButtonVariant = 'filled';
	export let size: Size = 'md';
	interface Classes {
		root: string;
		inner: string;
		label: string;
	}
	export let classes: Partial<Classes> = {};
</script>

<button
	class="[ button ] [ {classes.root || ''} ]"
	on:click
	data-variant={variant}
	data-size={size}
	data-color={color}
>
	<div class="[ button-inner ] [ {classes.inner || ''} ]">
		<span class="[ button-label ] [ {classes.label || ''} ]"><slot /></span>
	</div>
</button>
